version: 2.1

install_nodejs: &install_nodejs
  - checkout
  - run: |
      echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
      echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
  - run: |
      node -v
  - run: |
      nvm install v10
      node -v
      nvm alias default v10
  - run: |
      node -v

jobs:
  compile:
    docker:
      - image: hseeberger/scala-sbt:8u222_1.3.6_2.12.10
    environment:
      SBT_VERSION: 1.3.6
    working_directory: ~/Proptics

    steps:
      - checkout
      - <<: *install_nodejs
      - run:
          name: Assembly a JAR package
          command: |
            sbt ";test;compile"

workflows:
  version: 2
  build:
    jobs:
      - compile:
          filters:
            tags:
              ignore: /^v.*/
            branches:
              only: /.*/