version: 2.1

install_nodejs: &install_nodejs
  - run:
      name: Install node.js
      command: |
        export NVM_DIR="/opt/circleci/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install
        nvm use
        node -v

jobs:
  compile:
    docker:
      - image: hseeberger/scala-sbt:8u222_1.3.6_2.12.10
    environment:
      SBT_VERSION: 1.3.6
    working_directory: ~/Proptics

    steps:
      - checkout
      - <<: *install_nodejs
      - run:
          name: Assembly a JAR package
          command: |
            sbt ";test;compile"

workflows:
  version: 2
  build:
    jobs:
      - compile:
          filters:
            tags:
              ignore: /^v.*/
            branches:
              only: /.*/