version: 2.1

orbs:
  node: circleci/node@x.y

jobs:
  install-nodejs: &install-node
    steps:
      - node/install:
          install-yarn: true
          node-version: latest
      - run: node --version

  compile:
    docker:
      - image: hseeberger/scala-sbt:8u222_1.3.6_2.12.10
    environment:
      SBT_VERSION: 1.3.6
    working_directory: ~/Proptics

    steps:
      - checkout
      - <<: *install-node
      - run:
          name: sbt compile
          command: |
            sbt ";test;compile"

workflows:
  version: 2
  build:
    jobs:
      - compile:
          filters:
            tags:
              ignore: /^v.*/
            branches:
              only: /.*/